name: Python Tests

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

permissions: write-all

jobs:
  build_and_test:
    name: Build & Test
    uses: p6m-dev/github-actions/.github/workflows/test-python.yaml@main
    secrets:
      ARTIFACTORY_USERNAME: ${{'{'}}{ secrets.ARTIFACTORY_USERNAME }}
      ARTIFACTORY_IDENTITY_TOKEN: ${{'{'}}{ secrets.ARTIFACTORY_IDENTITY_TOKEN }}